Metrics/AbcSize:
  Max: 20

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/PerceivedComplexity:
  Max: 10

Metrics/LineLength:
  Max: 120

Style/GuardClause:
  Enabled: false

Metrics/MethodLength:
  Max: 20
